enum OPCODES
{
  OP_NOP,
  OP_LXI_B,
  OP_STAX_B,
  OP_INX_B,
  OP_INR_B,
  OP_DCR_B,
  OP_MVI_B,
  OP_RLC,
  OP_INVAL_1,
  OP_DAD_B,
  OP_LDAX_B,
  OP_DCX_B,
  OP_INR_C,
  OP_DCR_C,
  OP_MVI_C,
  OP_RRC,
  OP_INVAL_2,
  OP_LXI_D,
  OP_STAX_D,
  OP_INX_D,
  OP_INR_D,
  OP_DCR_D,
  OP_MVI_D,
  OP_RAL,
  OP_INVAL_3,
  OP_DAD_D,
  OP_LDAX_D,
  OP_DCX_D,
  OP_INR_E,
  OP_DCR_E,
  OP_MVI_E,
  OP_RAR,
  OP_INVAL_4,
  OP_LXI_H,
  OP_SHLD,
  OP_INX_H,
  OP_INR_H,
  OP_DCR_H,
  OP_MVI_H,
  OP_DAA,
  OP_INVAL_5,
  OP_DAD_H,
  OP_LHLD,
  OP_DCX_H,
  OP_INR_L,
  OP_DCR_L,
  OP_MVI_L,
  OP_CMA,
  OP_INVAL_6,
  OP_LXI_SP,
  OP_STA,
  OP_INX_SP,
  OP_INR_M,
  OP_DCR_M,
  OP_MVI_M,
  OP_STC,
  OP_INVAL_7,
  OP_DAD_SP,
  OP_LDA,
  OP_DCX_SP,
  OP_INR_A,
  OP_DCR_A,
  OP_MVI_A,
  OP_CMC,
  OP_MOV_B_B,
  OP_MOV_B_C,
  OP_MOV_B_D,
  OP_MOV_B_E,
  OP_MOV_B_H,
  OP_MOV_B_L,
  OP_MOV_B_M,
  OP_MOV_B_A,
  OP_MOV_C_B,
  OP_MOV_C_C,
  OP_MOV_C_D,
  OP_MOV_C_E,
  OP_MOV_C_H,
  OP_MOV_C_L,
  OP_MOV_C_M,
  OP_MOV_C_A,
  OP_MOV_D_B,
  OP_MOV_D_C,
  OP_MOV_D_D,
  OP_MOV_D_E,
  OP_MOV_D_H,
  OP_MOV_D_L,
  OP_MOV_D_M,
  OP_MOV_D_A,
  OP_MOV_E_B,
  OP_MOV_E_C,
  OP_MOV_E_D,
  OP_MOV_E_E,
  OP_MOV_E_H,
  OP_MOV_E_L,
  OP_MOV_E_M,
  OP_MOV_E_A,
  OP_MOV_H_B,
  OP_MOV_H_C,
  OP_MOV_H_D,
  OP_MOV_H_E,
  OP_MOV_H_H,
  OP_MOV_H_L,
  OP_MOV_H_M,
  OP_MOV_H_A,
  OP_MOV_L_B,
  OP_MOV_L_C,
  OP_MOV_L_D,
  OP_MOV_L_E,
  OP_MOV_L_H,
  OP_MOV_L_L,
  OP_MOV_L_M,
  OP_MOV_L_A,
  OP_MOV_M_B,
  OP_MOV_M_C,
  OP_MOV_M_D,
  OP_MOV_M_E,
  OP_MOV_M_H,
  OP_MOV_M_L,
  OP_HLT,
  OP_MOV_M_A,
  OP_MOV_A_B,
  OP_MOV_A_C,
  OP_MOV_A_D,
  OP_MOV_A_E,
  OP_MOV_A_H,
  OP_MOV_A_L,
  OP_MOV_A_M,
  OP_MOV_A_A,
  OP_ADD_B,
  OP_ADD_C,
  OP_ADD_D,
  OP_ADD_E,
  OP_ADD_H,
  OP_ADD_L,
  OP_ADD_M,
  OP_ADD_A,
  OP_ADC_B,
  OP_ADC_C,
  OP_ADC_D,
  OP_ADC_E,
  OP_ADC_H,
  OP_ADC_L,
  OP_ADC_M,
  OP_ADC_A,
  OP_SUB_B,
  OP_SUB_C,
  OP_SUB_D,
  OP_SUB_E,
  OP_SUB_H,
  OP_SUB_L,
  OP_SUB_M,
  OP_SUB_A,
  OP_SBB_B,
  OP_SBB_C,
  OP_SBB_D,
  OP_SBB_E,
  OP_SBB_H,
  OP_SBB_L,
  OP_SBB_M,
  OP_SBB_A,
  OP_ANA_B,
  OP_ANA_C,
  OP_ANA_D,
  OP_ANA_E,
  OP_ANA_H,
  OP_ANA_L,
  OP_ANA_M,
  OP_ANA_A,
  OP_XRA_B,
  OP_XRA_C,
  OP_XRA_D,
  OP_XRA_E,
  OP_XRA_H,
  OP_XRA_L,
  OP_XRA_M,
  OP_XRA_A,
  OP_ORA_B,
  OP_ORA_C,
  OP_ORA_D,
  OP_ORA_E,
  OP_ORA_H,
  OP_ORA_L,
  OP_ORA_M,
  OP_ORA_A,
  OP_CMP_B,
  OP_CMP_C,
  OP_CMP_D,
  OP_CMP_E,
  OP_CMP_H,
  OP_CMP_L,
  OP_CMP_M,
  OP_CMP_A,
  OP_RNZ,
  OP_POP_B,
  OP_JNZ,
  OP_JMP,
  OP_CNZ,
  OP_PUSH_B,
  OP_ADI,
  OP_RST_0,
  OP_RZ,
  OP_RET,
  OP_JZ,
  OP_INVAL_8,
  OP_CZ,
  OP_CALL,
  OP_ACI,
  OP_RST_1,
  OP_RNC,
  OP_POP_D,
  OP_JNC,
  OP_OUT,
  OP_CNC,
  OP_PUSH_D,
  OP_SUI,
  OP_RST_2,
  OP_RC,
  OP_INVAL_9,
  OP_JC,
  OP_IN,
  OP_CC,
  OP_INVAL_10,
  OP_SBI,
  OP_RST_3,
  OP_RPO,
  OP_POP_H,
  OP_JPO,
  OP_XTHL,
  OP_CPO,
  OP_PUSH_H,
  OP_ANI,
  OP_RST_4,
  OP_RPE,
  OP_PCHL,
  OP_JPE,
  OP_XCHG,
  OP_CPE,
  OP_INVAL_11,
  OP_XRI,
  OP_RST_5,
  OP_RP,
  OP_POP_PSW,
  OP_JP,
  OP_DI,
  OP_CP,
  OP_PUSH_PSW,
  OP_ORI,
  OP_RST_6,
  OP_RM,
  OP_SPHL,
  OP_JM,
  OP_EI,
  OP_CM,
  OP_EXIT,
  OP_CPI,
  OP_RST_7
};

static const uint8_t op_cycles[] = {
  4,  10, 7,  5,  5,  5,  7,  4,  4,  10, 7,  5,  5,  5,  7,  4,  4,  10, 7,
  5,  5,  5,  7,  4,  4,  10, 7,  5,  5,  5,  7,  4,  4,  10, 16, 5,  5,  5,
  7,  4,  4,  10, 16, 5,  5,  5,  7,  4,  4,  10, 13, 5,  10, 10, 10, 4,  4,
  10, 13, 5,  5,  5,  7,  4,  5,  5,  5,  5,  5,  5,  7,  5,  5,  5,  5,  5,
  5,  5,  7,  5,  5,  5,  5,  5,  5,  5,  7,  5,  5,  5,  5,  5,  5,  5,  7,
  5,  5,  5,  5,  5,  5,  5,  7,  5,  5,  5,  5,  5,  5,  5,  7,  5,  7,  7,
  7,  7,  7,  7,  7,  7,  5,  5,  5,  5,  5,  5,  7,  5,  4,  4,  4,  4,  4,
  4,  7,  4,  4,  4,  4,  4,  4,  4,  7,  4,  4,  4,  4,  4,  4,  4,  7,  4,
  4,  4,  4,  4,  4,  4,  7,  4,  4,  4,  4,  4,  4,  4,  7,  4,  4,  4,  4,
  4,  4,  4,  7,  4,  4,  4,  4,  4,  4,  4,  7,  4,  4,  4,  4,  4,  4,  4,
  7,  4,  5,  10, 10, 10, 11, 11, 7,  11, 5,  10, 10, 10, 11, 17, 7,  11, 5,
  10, 10, 10, 11, 11, 7,  11, 5,  10, 10, 10, 11, 17, 7,  11, 5,  10, 10, 18,
  11, 11, 7,  11, 5,  5,  10, 4,  11, 17, 7,  11, 5,  10, 10, 4,  11, 11, 7,
  11, 5,  5,  10, 4,  11, 17, 7,  11
};

static const char* op_name[] = {
  "nop",      "lxi b,#", "stax b",  "inx b",   "inr b",   "dcr b",   "mvi b,#",
  "rlc",      "ill",     "dad b",   "ldax b",  "dcx b",   "inr c",   "dcr c",
  "mvi c,#",  "rrc",     "ill",     "lxi d,#", "stax d",  "inx d",   "inr d",
  "dcr d",    "mvi d,#", "ral",     "ill",     "dad d",   "ldax d",  "dcx d",
  "inr e",    "dcr e",   "mvi e,#", "rar",     "ill",     "lxi h,#", "shld",
  "inx h",    "inr h",   "dcr h",   "mvi h,#", "daa",     "ill",     "dad h",
  "lhld",     "dcx h",   "inr l",   "dcr l",   "mvi l,#", "cma",     "ill",
  "lxi sp,#", "sta $",   "inx sp",  "inr M",   "dcr M",   "mvi M,#", "stc",
  "ill",      "dad sp",  "lda $",   "dcx sp",  "inr a",   "dcr a",   "mvi a,#",
  "cmc",      "mov b,b", "mov b,c", "mov b,d", "mov b,e", "mov b,h", "mov b,l",
  "mov b,M",  "mov b,a", "mov c,b", "mov c,c", "mov c,d", "mov c,e", "mov c,h",
  "mov c,l",  "mov c,M", "mov c,a", "mov d,b", "mov d,c", "mov d,d", "mov d,e",
  "mov d,h",  "mov d,l", "mov d,M", "mov d,a", "mov e,b", "mov e,c", "mov e,d",
  "mov e,e",  "mov e,h", "mov e,l", "mov e,M", "mov e,a", "mov h,b", "mov h,c",
  "mov h,d",  "mov h,e", "mov h,h", "mov h,l", "mov h,M", "mov h,a", "mov l,b",
  "mov l,c",  "mov l,d", "mov l,e", "mov l,h", "mov l,l", "mov l,M", "mov l,a",
  "mov M,b",  "mov M,c", "mov M,d", "mov M,e", "mov M,h", "mov M,l", "hlt",
  "mov M,a",  "mov a,b", "mov a,c", "mov a,d", "mov a,e", "mov a,h", "mov a,l",
  "mov a,M",  "mov a,a", "add b",   "add c",   "add d",   "add e",   "add h",
  "add l",    "add M",   "add a",   "adc b",   "adc c",   "adc d",   "adc e",
  "adc h",    "adc l",   "adc M",   "adc a",   "sub b",   "sub c",   "sub d",
  "sub e",    "sub h",   "sub l",   "sub M",   "sub a",   "sbb b",   "sbb c",
  "sbb d",    "sbb e",   "sbb h",   "sbb l",   "sbb M",   "sbb a",   "ana b",
  "ana c",    "ana d",   "ana e",   "ana h",   "ana l",   "ana M",   "ana a",
  "xra b",    "xra c",   "xra d",   "xra e",   "xra h",   "xra l",   "xra M",
  "xra a",    "ora b",   "ora c",   "ora d",   "ora e",   "ora h",   "ora l",
  "ora M",    "ora a",   "cmp b",   "cmp c",   "cmp d",   "cmp e",   "cmp h",
  "cmp l",    "cmp M",   "cmp a",   "rnz",     "pop b",   "jnz $",   "jmp $",
  "cnz $",    "push b",  "adi #",   "rst 0",   "rz",      "ret",     "jz $",
  "ill",      "cz $",    "call $",  "aci #",   "rst 1",   "rnc",     "pop d",
  "jnc $",    "out p",   "cnc $",   "push d",  "sui #",   "rst 2",   "rc",
  "ill",      "jc $",    "in p",    "cc $",    "ill",     "sbi #",   "rst 3",
  "rpo",      "pop h",   "jpo $",   "xthl",    "cpo $",   "push h",  "ani #",
  "rst 4",    "rpe",     "pchl",    "jpe $",   "xchg",    "cpe $",   "ill",
  "xri #",    "rst 5",   "rp",      "pop psw", "jp $",    "di",      "cp $",
  "push psw", "ori #",   "rst 6",   "rm",      "sphl",    "jm $",    "ei",
  "cm $",     "ill",     "cpi #",   "rst 7"
};
